### ISSUE TITLE
Wow.

### ISSUE THREAD

**Issue by nulledsenpai** [JunkBeat/Anti-AFK-GUI#1]
So I've tried a few different tools to avoid the idle kick and they were all inconvenient and or had issues.

This one was incredibly well made, thank you! I wish I knew more about how you did this, genuinely gives me the itch to learn to code but wouldn't know where to start...

**Feedback**

"Activity type set to Jump" - Had a few disconnects, multiple nights, setting it to "Camera movement" stopped these completely.
"Make target window transparent" - Sometimes a client hung/froze after extended periods of time, wasn't sure if it was due to this

Didn't really use "Open screensaver [Night farm]", as the beauty of this tool for me was being able to actually turn off my displays, since I have 3, so I would set my display to turn off after 1 minute in Power Options. Could incorporate this into the tool but not really necessary of course!

It would be cool if during the "Activity Window" the inputs sent to Roblox didn't interfere with general use, but I assume this isn't really possible?

**Comment by JunkBeat** [comment]
Hello. Thank you for the detailed feedback; it is truly motivating. Actually, the code needs some refinement as it is poorly organized, but in any case, I will strive to improve the program.

If you want to learn how to code, perhaps you should start with some small projects.  There are many articles, books, projects that can help you improve your knowledge and practice.

> "Activity type set to Jump" - Had a few disconnects, multiple nights, setting it to "Camera movement" stopped these completely. 

The same thing was happening to me in Roblox. I don't know why, as the same function is responsible for button presses. I am currently figuring out whether it's related to my program or, indeed, to Roblox.

> "Make target window transparent" - Sometimes a client hung/froze after extended periods of time

What exactly do you mean? Can you provide more details please?

> I would set my display to turn off after 1 minute in Power Options. Could incorporate this into the tool.

Good idea. Of course, there are other utilities for this, but I will try to implement it.

> It would be cool if during the "Activity Window" the inputs sent to Roblox didn't interfere with general use.

Unfortunately, this is not possible. It is necessary to make the window active and bring it to the foreground to interact with it. For convenience, you can either monitor window appearances through notifications or block input to avoid interfering with Anti-AFK functionality.

**Comment by nulledsenpai** [comment]
> What exactly do you mean? Can you provide more details please?

When "Make target window transparent" was enabled, a few times, an instance appeared to not maximize and was blank? so I had to exit the instance of Roblox and reopen. But it could be unrelated to that function, I didn't test it enough.

> Unfortunately, this is not possible. It is necessary to make the window active and bring it to the foreground to interact with it. For convenience, you can either monitor window appearances through notifications or block input to avoid interfering with Anti-AFK functionality.

Yeah shame really, I've been looking endlessly into finding a way, since it would at least allow me to set Roblox aside and work on other things. I know some Emulator's have built in macro functionality that can achieve this, however I only tried Bluestacks and clients regularly crash and run at 15 frames! :)

**Comment by nulledsenpai** [comment]
Also great fixes! I noticed all of those but they didn't affect my use much ^^

**Comment by Opticai1** [comment]
Hi, I would also like to leave a comment that this program is really really helpful. I've been looking for something like this for a long time with the feature of leaving Roblox and the inputs in the background. I don't know how this hasn't reached thousands of people yet. Thank you and keep up the good work!

**Comment by STEEPERCREVE** [comment]
Adding on to this, a few months late, but despite its relative simplicity its great. works fine. also, as of this current time you cannot send inputs to roblox without focusing the windows as they detect and block it, if you were intending to add that. overall good, keep adding to it i guess

**Comment by CodeByAidan** [comment]
> despite its relative simplicity its great

It's a script. Add it yourself, close this issue.

**Comment by JunkBeat** [comment]
Guys, I have released a new and improved AntiAFK program for Roblox:
https://github.com/JunkBeat/AntiAFK-Roblox
